### ISSUE TITLE
T_L values appear to be missing

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#109]

**Comment by emartinez-usgs** [comment]
Data is just missing on one of the dev servers.

**Comment by smcgowan-usgs** [comment]
This seems to be resolved (checked in FF and Chrome).

**Comment by emartinez-usgs** [comment]
Just need to reload data on dev servers once #111 and #112 are complete.

**Comment by emartinez-usgs** [comment]
There was no code changed as part of this request, but data was loaded on the dev system. To verify, check dev system report output to ensure TL "Long-Period Transition Period " data is present.

**Comment by ehunter-usgs** [comment]
I seent it
