### ISSUE TITLE
Update site class labels

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#111]
- Change `B` to `B (measured)`
- Change `B-U` to `B (unmeasured)`
- Change `U-D` to `D (default)`
- Change `D` to `D (determined`

**Comment by smcgowan-usgs** [comment]
Change D to D (determined)

**Comment by smcgowan-usgs** [comment]
This change applies to the Site Class drop-down input menu as well as the Fa and Fv tables in the output report.
