### ISSUE TITLE
Enable site class E as an option

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#112]
Some code already exists in SiteAmplification.js and is commented out. Uncomment that code and potentially other actions are required.

Fa coefficients (`ssInfo`) should be adjusted to use the following values:
2.4, 1.7, 1.3, 1.2, 1.2, 1.2

Values for Fv and Fpga remain unchanged.

**Comment by smcgowan-usgs** [comment]
Ideally should be displayed as: 2.4 1.7 1.3 1.2* 1.2* 1.2*, where * is actually a superscripted "1" to point to Footnote 1 in ticket #113.

**Comment by smcgowan-usgs** [comment]
In Site Class dropdown input menu, should be listed as "E: soft clay soil". Keep formatting/capitalization/etc. consistent with existing Site Class options.

**Comment by smcgowan-usgs** [comment]
Fv coefficients:
4.2 3.3* 2.8* 2.4* 2.2* 2.0*, with * also referencing Footnote 1.
