### ISSUE TITLE
Site amplification footnotes

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#113]
Add footnotes below the site amplification (Fa/Fv/Fpga) tables:

Fa
---
- <sup>*</sup> See requirements for site-specific ground motions in Section 11.4.7. Here the exception allowing use of the Site Class C values of F<sub>a</sub> has been invoked.
- Note: Use straight-line interpolation for intermediate values of S<sub>S</sub>.
- Note: Where Site Class B is selected, but site-specific velocity measurements are not made, the values of F<sub>a</sub> shall be taken as 1.0 per Section 11.4.2.
- Note: Where Site Class D is selected as the default site class per Section 11.4.2, the values of F<sub>a</sub> shall not be less than 1.2 per Section 11.4.3.

Fv
---
- <sup>1</sup> Also, see requirements for site-specific ground motions in Section 11.4.7.
- Note: Use straight-line interpolation for intermediate values of S<sub>1</sub>.
- Note: Where Site Class B is selected, but site-specific velocity measurements are not made, the values of F<sub>v</sub> shall be taken as 1.0 per Section 11.4.2.

Keep current footnotes below Fpga table.

**Comment by smcgowan-usgs** [comment]
For 3rd bullet under both Fa and Fv: change "values" to "value".  This was my typo, sorry.

**Comment by emartinez-usgs** [comment]
The footnotes are duplicated now. I merged the PR because everything else was good and it closed many other tickets, however this particular issue needs some more attention.
