### ISSUE TITLE
Update Fv coefficients for site class D

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#114]
Use the following values:

2.4, 2.2, 2.0, 1.9, 1.8, 1.7

@smcgowan-usgs Does this apply to both "D (determined)" and "D (default)" or just one or the other?

**Comment by smcgowan-usgs** [comment]
I just doublechecked and confirmed that this applies to D (default) and D (determined).

**Comment by smcgowan-usgs** [comment]
Ideally should be displayed as: 2.4 2.2* 2.0* 1.9* 1.8* 1.7*, where * is actually a superscripted "1" to point to Footnote 1 in ticket #113.

**Comment by emartinez-usgs** [comment]
Coefficients are currently correct, but the superscript needs to be added.
