### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#117]
When errors occur, typically due to lack of selecting a value for an input, but other errors as well.

Do something similar to what was done for the usgs/earthquake-hazard-tool application.

**Comment by smcgowan-usgs** [comment]
One specific example: a "Title" is require user input

**Comment by smcgowan-usgs** [comment]
Another: please notify user that a location input has not been selected if that is the case.

**Comment by emartinez-usgs** [comment]
A modal error box should appear if...
- the "Calculate" button is clicked and a calculation does not trigger (due to incomplete inputs typically), a  warning error should appear
- an XHR request fails or returns bad data

Error box should be informative enough that they can correct any potential user error.

**Comment by emartinez-usgs** [comment]
It looks like error handling was never merged in to the main usgs/earthquake-hazard-tool application. There is an open issue and pull request that might be useful for reference:

- https://github.com/usgs/earthquake-hazard-tool/issues/91
- https://github.com/usgs/earthquake-hazard-tool/pull/117

**Comment by smcgowan-usgs** [comment]
It looks like the application chokes when the pin drop is used to specify the location for analysis. The specified location does not seem to get recorded as a Lat/Long coordinate pair.
 
![screen shot 2016-01-29 at 10 52 59 am](https://cloud.githubusercontent.com/assets/1851280/12683469/aa1ee73a-c676-11e5-993f-f329a3ab291f.png)

**Comment by ehunter-usgs** [comment]
This is not an issue. We were in the process of deploying the application to development and things were broken.
