### ISSUE TITLE
Add a disclaimer...

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#118]
... between summary output section and initial spectra output. Only add this summary output if the site class is "D (determined)", "D (default)" or "E". The disclaimer should use the "alert warning" class.

Use this text:

```
Since Site Class D has been selected, see the requirements for site-specific ground motions in Section 11.4.7.
```

Note: Use the site class that was actually selected.

**Comment by smcgowan-usgs** [comment]
Change to "Site Class D or E..."
