### ISSUE TITLE
Add superscripts to Fa/Fv tables

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#119]
Fa
---

- Site Class E should have a superscript "*" in the last three columns.

Fv
---
- Site Class D should have a superscript "1" in all but the first column.
- Site Class E should have a superscript "1" in all but the first column.

@smcgowan-usgs Does this apply to both "D (default)" as well as "D (determined)" ?

**Comment by smcgowan-usgs** [comment]
Yes, it applies to D (default) and D (determined).

**Comment by smcgowan-usgs** [comment]
I just changed the Fa Site Class E superscript to "2".

**Comment by emartinez-usgs** [comment]
Please update the related footnote ticket as well, or otherwise clarify what the [2] footnote should explain.

**Comment by smcgowan-usgs** [comment]
Note: I had changed the Fa superscript to [2], but realized that is incorrect. Please keep as [1].
