### ISSUE TITLE
Investigate how spectra are plotted when SM1 > SMS

### ISSUE THREAD

**Issue by smcgowan-usgs** [usgs/earthquake-usdesign#120]
When this happens, SMS should be set equal to SM1 on the spectra plot. This should then be carried through for SDS and SD1. Note: this only applies for plotting purposes....not for the reported values appearing anywhere else in the output report.

**Comment by emartinez-usgs** [comment]
@smcgowan-usgs Can you provide an example location where this happens so we can verify when this is corrected?

**Comment by smcgowan-usgs** [comment]
Here are some sites where this would trigger:
32.7651, -117.2258
33.7444, -118.2776
33.7606, -118.2359

**Comment by smcgowan-usgs** [comment]
...these cause the spectra problem for 2012 IBC values. Hard to confirm the error in Beta application as-is (without Site Class E available in GUI), but let me know if they don't trigger the same problem for 2015 NEHRP and I'll provide some additional test sites.

**Comment by jdbrown-USGS** [comment]
I can't reproduce this problem with the locations given using 2015 NEHRP data.

**Comment by smcgowan-usgs** [comment]
I tried a bunch of additional locations but was also unable to reproduce the error for 2015 NEHRP data. Let's assume this is working well and we can make adjustments if needed at a later date. It will take more time than we have available before launching, but in the coming weeks I can probably do some reverse engineering to track down coordinates where this could be triggered.
