### ISSUE TITLE
Add logos for collaborating organizations

### ISSUE THREAD

**Issue by smcgowan-usgs** [usgs/earthquake-usdesign#121]
These include: FEMA, BSSC, ASCE, and NEHRP. Sean to provide image files.

**Comment by emartinez-usgs** [comment]
Where and how would these logos be added? Can these go on documentation pages? We have a standardized method for adding a single collaborator when data comes from a single source, but not sure about how we might handle attribution for four collaborators at once.

**Comment by smcgowan-usgs** [comment]
We have some options:
-If only one logo can be listed, it should be NEHRP
-If 2, then USGS and FEMA
-If 4, then USGS, FEMA, BSSC, and ASCE
I think our preferred option would be to just add FEMA (for 2 logos, including ours) on the application page (not sure where, but we can discuss this). But, in the event we get pressure to add all 4 (and if being mentioned in the Documentation isn't "good enough") it would be good to know if this is at least a realistic possibility.

**Comment by emartinez-usgs** [comment]
Let's assume the FEMA logo next to the USGS logo for now. Check with FEMA to see if they provide guidance on how to provide attribution.

**Comment by emartinez-usgs** [comment]
@smcgowan-usgs Please contact FEMA and get approval to place their logo on this page. it will appear to the right of the USGS logo in the top-left corner of the page. The logo we intend to use is the DHS seal with the blue FEMA text.

**Comment by smcgowan-usgs** [comment]
Ok, I've submitted a request to our NEHRP contact at FEMA. I'll let you guys know ASAP once I hear back from him.

**Comment by smcgowan-usgs** [comment]
Nico tracked down a recent email from FEMA where they stated a preference for using the same logo you have described for a design-related Powerpoint presentation. We should proceed with the DHS seal + FEMA block letters logo.

**Comment by smcgowan-usgs** [comment]
Email from Mike Tong, at FEMA HQ:
_Sean,
It is fine to add FEMA logo next to USGS logo for the US Seismic Design Maps..[...]...The DHS logo and FEMA label should go together. Hope to meet you again soon.
Best,                                             
Mike Tong_
