### ISSUE TITLE
Add/Update Notes/Disclaimers

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#138]
All these notes should be styled in a manner consistent with current disclaimer/note styles.

In the summary section when site class "E" is selected and S<sub>S</sub> &ge; 1.0 g add a superscript <sup>*</sup> after the "g" on the S<sub>MS</sub> and S<sub>DS</sub> values. Additionally under this condition, add a footnote with the "Fa Note" text (see below).

In the summary section when site class "E" or "D" is selected and S<sub>1</sub> &ge; 0.2 g add a superscript <sup>1</sup> after the "g" on the S<sub>M1</sub> and S<sub>D1</sub> values. Additionally under this condition, add a footnote with the "Fv Note" text (see below).

In the summary section, when S<sub>MS</sub> is less than S<sub>M1</sub> add a note below the MCE<sub>R</sub> Spectrum with the "Spectra Note" text (see below).

In the summary section, when S<sub>DS</sub> is less than S<sub>D1</sub> add a note below the Design Response Spectrum with the "Spectra Note" text (see below).

Change the superscripts in the Fa table to be <sup>*</sup>.
Update the footnote below the Fa table with the "Fa Note" text (see below). Remove the condition qualifier and start the footnote with "<sup>*</sup> See the &hellip;".

Update the footnote below the Fv table with the "Fv Note" text (see below). Remove the condition qualifier and start the footnote with "<sup>1</sup> Site-specific&hellip;"

When S<sub>DS</sub> is less than S<sub>D1</sub> add a note below the "Figure 11.4.1: Design Response Spectrum" header with the "Spectra Note" text (see below).

When S<sub>MS</sub> is less than S<sub>M1</sub> add a note below the existing note in the large MCE<sub>R</sub> Spectrum section with the "Spectra Note" text (see below).

### Disclaimer Definitions

**Fa Note**
<sup>*</sup> Since the Site Class is {X} and S<sub>S</sub> &ge; 1.0 g, see the requirements for site-specific ground motions in Section 11.4.7. Here the exception allowing use of the Fa values for Site Class C has been invoked.

**Fv Note**
<sup>1</sup> Since the Site Class is {X} and S<sub>1</sub> &ge; 0.2 g, site-specific ground motions might be required. See Section 11.4.7.

**Spectra Note**
Since S<sub>MS</sub> &lt; S<sub>M1</sub>, for this response spectrum S<sub>MS</sub> has been set equal to S<sub>M1</sub> (and hence S<sub>DS</sub> has been set equal to S<sub>D1</sub>), in accordance with Section 11.4.3.

_Only add parenthetical portion (keep parentheses) on the design spectrum note._

**Comment by ehunter-usgs** [comment]
**Fa Note, forgot the subscript on SS**

* Since the Site Class is E and SS ≥ 1.0 g, see the requirements for site-specific ground motions in Section 11.4.7. Here the exception allowing use of the Fa values for Site Class C has been invoked.


**Fa & Fv Table subscript, if you start a line with a superscript I would provide a space after the superscript** 

<sup>1</sup> Site-specific ground motions…


**Figure 11.4-1,  capitalize the "S" for  S<sub>DS</sub> and S<sub>D1</sub> values**

Since SMS < SM1, for this response spectrum SMS has been set equal to SM1 (and hence sDS has been set equal to sD1), in accordance with Section 11.4.3.
