### ISSUE TITLE
Site Class E superscript fires unnecessarily

### ISSUE THREAD

**Issue by smcgowan-usgs** [usgs/earthquake-usdesign#144]
The Site Class E superscript [1] seems to fire on the summary data at the beginning of the output report even if the S1 threshold of 0.2g is not met. Please see screenshot attached.
![site class e superscript](https://cloud.githubusercontent.com/assets/1851280/12690059/19d0946c-c69e-11e5-988d-b9a42674fd13.png)

**Comment by ehunter-usgs** [comment]
@smcgowan-usgs should the superscript [1] also appear for Site Class D or only for Site Class E?

**Comment by emartinez-usgs** [comment]
It should fire for both D and E.

**Comment by smcgowan-usgs** [comment]
Just confirming that Eric's comment is indeed correct. Yes, the superscript for this case should be [1]. Thanks guys.
