### ISSUE TITLE
Change [1] superscript to [*] in Fa table

### ISSUE THREAD

**Issue by smcgowan-usgs** [usgs/earthquake-usdesign#146]
In the Fa table, the [1] superscripts in the last 3 columns of the Site Class E row should be [*]. This should also carry through to the superscript information below the Fa table.

**Comment by ehunter-usgs** [comment]
@smcgowan-usgs should superscript text after the table reference Site Class E instead of,

```* See the requirements for site-specific ground motions in Section 11.4.7. Here the exception allowing use of the Fa values for Site Class C has been invoked.```
