### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#55]
- The "g" in "eg. Essential Facilities" in the "Risk Category" drop down box is clipped (Firefox)

- Adjust layout width so figures/tables etc... are not clipped when printing.

**Comment by ehunter-usgs** [comment]
fixes firefox inconsistency
 - https://github.com/usgs/hazdev-template/pull/108
adjusts print layout
 - https://github.com/usgs/earthquake-usdesign/pull/83
