### ISSUE TITLE
getS1d Bug

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#57]
It looks like there is a typo in the getS1d function in the NEHRP calculator.

"percentil_s1" --> "percentile_s1"

Correct this and then ensure correct values are returned for S1D in the generated report. For example, try:

34.05N, 118.25W. This should produce an S1D value (Equation 11.4-4) of ~0.786g. Currently it outputs 0.6g.

**Comment by jdbrown-USGS** [comment]
- fixes usgs/earthquake-usdesign#57
- fixes usgs/earthquake-usdesign#56

This ticket is done here along with ticket # 56 
pull request https://github.com/usgs/earthquake-usdesign/pull/75

**Comment by jmfee-usgs** [comment]
fixed by #75
