### ISSUE TITLE
Verify/Correct Figure Labels/Links

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-usdesign#63]
For each region, for each data type.

Verify using the following document:
http://www.fema.gov/media-library-data/1437762555387-0805e1ee9059761018259b56fdc58d68/fema_p-1050-1.pdf

Figures configured in these files:
Nehrp2015Section_11_4_1
Nehrp2015Section_11_4_5

Get updated figures uploaded to web server and ensure links are all correct.

**Comment by emartinez-usgs** [comment]
Comment on PR.

**Comment by emartinez-usgs** [comment]
Figures are available here: ftp://ftpext.usgs.gov/pub/cr/co/golden/Luco/2015nehrp/maps/

Also please ensure the link text we use in the report matches the actual figure title in the PDF.

These figures will likely need to be uploaded to the earthquake website in this section:
http://earthquake.usgs.gov/hazards/designmaps/pdfs/

**Comment by ehunter-usgs** [comment]
PDFs are on ehpdevel, in the process of pushing them into production
