### ISSUE TITLE
Temporarily remove Site Class E as an input option

### ISSUE THREAD

**Issue by smcgowan-usgs** [usgs/earthquake-usdesign#92]
This will be needed later, but requires a significant adjustment, so best to leave it out for now.

**Comment by emartinez-usgs** [comment]
Also, update site class labels as follows:

A: Hard rock
B: Rock
B-U: Rock, but unmeasured
C: Very dense soil and soft rock
D: Stiff soil
U-D: Undetermined (the default)

The B-U: Rock, but unmeasured is a new site class. This will require updating the site amplification calculator. All amplification factors for this site class are 1.0.
